# Site settings
title: Fathom Digital
email:
description: > # this means to ignore newlines until "baseurl:"
  Where Fathom Digital lives.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fathom.digital" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  FathomDigital

# Build settings
markdown: kramdown
